# Site settings
title: Øredev
email: noreply@oredev.org
baseurl: '/oredev-midsite'
url: https://frippz.github.io
permalink: pretty
paginate: 5

# Default page settings
defaults:
  -
    scope:
      path: ''
    values:
      author:

# Server settings
host: 0.0.0.0

# Gems
gems:
  - 'jekyll-archives'
  - 'jekyll-paginate'
  - 'rouge'

# Exclude
exclude:
  - 'node_modules'
  - 'script'
  - 'Makefile'
  - 'package.json'
  - 'lib'
  - 'site_config.mk'
  - 'LICENSE.md'
  - 'README.md'
  - 'src'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'yarn.lock'
